# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp1', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temp2', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temp3', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temp4', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
